import * as React from 'react';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import BottomNavigation from '@mui/material/BottomNavigation';
import BottomNavigationAction from '@mui/material/BottomNavigationAction';

import { useState, useRef } from 'react';
import RestoreIcon from '@mui/icons-material/Restore';
import FavoriteIcon from '@mui/icons-material/Favorite';
import ArchiveIcon from '@mui/icons-material/Archive';

import HomeOutlinedIcon from '@mui/icons-material/HomeOutlined';
import LocationOnOutlinedIcon from '@mui/icons-material/LocationOnOutlined';
import ChatBubbleOutlineOutlinedIcon from '@mui/icons-material/ChatBubbleOutlineOutlined';
import PersonOutlineOutlinedIcon from '@mui/icons-material/PersonOutlineOutlined';
import AddOutlinedIcon from '@mui/icons-material/AddOutlined';

import Paper from '@mui/material/Paper';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemAvatar from '@mui/material/ListItemAvatar';
import ListItemText from '@mui/material/ListItemText';
import Avatar from '@mui/material/Avatar';

// function refreshMessages(): MessageExample[] {
//   const getRandomInt = (max: number) =>
//     Math.floor(Math.random() * Math.floor(max));

//   return Array.from(new Array(50)).map(
//     () => messageExamples[getRandomInt(messageExamples.length)]
//   );
// }

export default function FixedBottomNavigation() {
  const [value, setValue] = useState(0);
  const ref = useRef<HTMLDivElement>(null);
  // const [messages, setMessages] = React.useState(() => refreshMessages());

  // React.useEffect(() => {
  //   (ref.current as HTMLDivElement).ownerDocument.body.scrollTop = 0;
  //   setMessages(refreshMessages());
  // }, [value, setMessages]);

  return (
    <Box sx={{ pb: 7 }} ref={ref}>
      <CssBaseline /> // 레이아웃 리셋
      <List>
        {/* {messages.map(({ primary, secondary, person }, index) => (
          <ListItem button key={index + person}>
            <ListItemAvatar>
              <Avatar alt="Profile Picture" src={person} />
            </ListItemAvatar>
            <ListItemText primary={primary} secondary={secondary} />
          </ListItem>
        ))} */}
      </List>
      <Paper
        sx={{ position: 'fixed', bottom: 0, left: 0, right: 0 }}
        elevation={3}
      >
        <BottomNavigation
          showLabels
          value={value}
          onChange={(event, newValue) => {
            setValue(newValue);
          }}
        >
          <BottomNavigationAction label="홈" icon={<HomeOutlinedIcon />} />
          <BottomNavigationAction
            label="내 주변"
            icon={<LocationOnOutlinedIcon />}
          />
          <BottomNavigationAction
            label="채팅"
            icon={<ChatBubbleOutlineOutlinedIcon />}
          />
          <BottomNavigationAction
            label="나의 N게더"
            icon={<PersonOutlineOutlinedIcon />}
          />
          <BottomNavigationAction
            label="N게더 모집"
            icon={<AddOutlinedIcon />}
          />
        </BottomNavigation>
      </Paper>
    </Box>
  );
}

interface MessageExample {
  primary: string;
  secondary: string;
  person: string;
}

const messageExamples: readonly MessageExample[] = [
  {
    primary: 'Brunch this week?',
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: '/static/images/avatar/5.jpg',
  },
  {
    primary: 'Birthday Gift',
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: '/static/images/avatar/1.jpg',
  },
  {
    primary: 'Recipe to try',
    secondary:
      'I am try out this new BBQ recipe, I think this might be amazing',
    person: '/static/images/avatar/2.jpg',
  },
  {
    primary: 'Yes!',
    secondary: 'I have the tickets to the ReactConf for this year.',
    person: '/static/images/avatar/3.jpg',
  },
  {
    primary: "Doctor's Appointment",
    secondary:
      'My appointment for the doctor was rescheduled for next Saturday.',
    person: '/static/images/avatar/4.jpg',
  },
  {
    primary: 'Discussion',
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: '/static/images/avatar/5.jpg',
  },
  {
    primary: 'Summer BBQ',
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: '/static/images/avatar/1.jpg',
  },
];

interface ProductExample {
  id: number;
  thumbnail: string | undefined;
  isOpen: boolean;
  title: string;
  price: string;
  spot: string;
}

const productList: readonly ProductExample[] = [
  {
    id: 1,
    thumbnail: '',
    isOpen: true,
    title: '아삭아삭 나주배 3kg',
    price: '9,850',
    spot: '서울 서초구',
  },
  {
    id: 2,
    thumbnail: '',
    isOpen: true,
    title: '남해안 디포리 멸치다시팩 15g * 20팩',
    price: '9,850',
    spot: '경기도 수지구',
  },
  {
    id: 3,
    thumbnail: '',
    isOpen: false,
    title: '23년 햅쌀 프리미엄 경기미  쌀 10kg',
    price: '9,850',
    spot: '제주 연동',
  },
  {
    id: 4,
    thumbnail: '',
    isOpen: true,
    title: '호주산 냉장 소고기 모듬구이 세트 600',
    price: '9,850',
    spot: '서울 서초구',
  },
  {
    id: 5,
    thumbnail: '',
    isOpen: false,
    title: '헤이즈 파스텔 확장형 캐리어',
    price: '9,850',
    spot: '서울 서초구',
  },
  {
    id: 6,
    thumbnail: '',
    isOpen: false,
    title: '프라우반 독일산 젤락스 Welfare-Relax 베개/베개커버',
    price: '15,120',
    spot: '서울 서초구',
  },
  {
    id: 7,
    thumbnail: '',
    isOpen: true,
    title: '송이송송 자연한톨 코인육수/자연톡톡 분말육수',
    price: '32,850',
    spot: '서울 서초구',
  },
  {
    id: 8,
    thumbnail: '',
    isOpen: true,
    title: '[명절명작]견과 선물세트 13호',
    price: '4,850',
    spot: '서울 서초구',
  },
  {
    id: 9,
    thumbnail: '',
    isOpen: false,
    title: '광동 초임계 알티지 오메가3 맥스',
    price: '19,850',
    spot: '서울 서초구',
  },
  {
    id: 10,
    thumbnail: '',
    isOpen: true,
    title: '[산들목장] 1+한우선물세트',
    price: '87,850',
    spot: '서울 서초구',
  },
];
